modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="callofequestria"
version="0.1.8"
displayName="Ponified"
authors="Bilivrayka"
displayTest="IGNORE_SERVER_VERSION"
description="ponified"
logoFile="logo.png"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.callofequestria]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
